import Footer from './Footer'
import Headers from './Headers'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Headers />
        <div className='container mx-auto my-5 min-h-screen'>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
